# Generated by Django 4.1.1 on 2022-10-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=900000),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
