version: "3.9"

services:
  db:
    image: postgres
    env_file: .env.local
    volumes:
      - database:/var/lib/postgresql/data/
  web:
    build: .
    command: python server/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/vclite
    ports:
      - 8000:8000
    env_file: .env.local
    depends_on:
      - db
volumes:
  database:
