# Generated by Django 4.1.1 on 2022-09-16 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                default=int,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.author",
            ),
            preserve_default=False,
        ),
    ]
