# Generated by Django 4.1.1 on 2022-09-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, default="last_name", max_length=30, null=True
            ),
        ),
    ]
