# Generated by Django 4.1.1 on 2022-10-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postextraimage",
            name="image",
            field=models.CharField(max_length=900000),
        ),
    ]
